### ISSUE TITLE
getting a numpy bool deprecation exception

### ISSUE THREAD

**Issue by psenin-sanofi** [labsyspharm/cylinter#145]
Hi folks:

When I install the CyLinter environment, 

`mamba create -n cylinter -c conda-forge -c labsyspharm cylinter`

numpy is resolving to 1.24:

`+ numpy                                1.24.4  py310ha4c1d20_0      conda-forge/linux-64     Cached`

but then later on I have a bool type not found exception:

```
/home/psenin/mambaforge/envs/cylinter/lib/python3.10/site-packages/cylinter/components.py:4519: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  df1 = df.where(np.triu(np.ones(df.shape)).astype(np.bool))
Traceback (most recent call last):
  File "/home/psenin/mambaforge/envs/cylinter/bin/cylinter", line 10, in <module>
    sys.exit(main())
  File "/home/psenin/mambaforge/envs/cylinter/lib/python3.10/site-packages/cylinter/cylinter.py", line 50, in main
    pipeline.run_pipeline(config, args.module)
  File "/home/psenin/mambaforge/envs/cylinter/lib/python3.10/site-packages/cylinter/pipeline.py", line 137, in run_pipeline
    data = module(data, qc, config)  # getattr(qc, module)
  File "/home/psenin/mambaforge/envs/cylinter/lib/python3.10/site-packages/cylinter/components.py", line 110, in wrapper
    result = func(*args, **kwargs)
  File "/home/psenin/mambaforge/envs/cylinter/lib/python3.10/site-packages/cylinter/components.py", line 4519, in PCA
    df1 = df.where(np.triu(np.ones(df.shape)).astype(np.bool))
  File "/home/psenin/mambaforge/envs/cylinter/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```

is there a way around this?

Thanks!

**Comment by gjbaker** [comment]
Hello and thank you for your message!

This error occurs because NumPy has recently deprecated its np.bool array type in favor of the standard Python bool. We will soon publish an updated conda recipe that avoids the error. In the meantime a quick fix is to change line 4519 in "/home/psenin/mambaforge/envs/cylinter/lib/python3.10/site-packages/cylinter/components.py" from "df1 = df.where(np.triu(np.ones(df.shape)).astype(np.bool))" to "df1 = df.where(np.triu(np.ones(df.shape)).astype('bool'))". Whereby the np.bool is simply substituted for the Python keyword, 'bool'.

**Comment by psenin-sanofi** [comment]
Thank you, Greg! It did help -- love how you gave a detailed fix explanation!

btw, a side question -- how to perform a positive ROI selection in the first Napari-driven step?

Thanks again!

**Comment by gjbaker** [comment]
Closing this issue, as a new conda recipe has been published for the latest CyLinter release (v0.0.47) which avoids this error.
