### ISSUE TITLE
Error during curate Thumbnail steps

### ISSUE THREAD

**Issue by fotisn7** [labsyspharm/cylinter#196]
Hello Cylinter Team,

Thank you for this great tool. I've encounter an error when trying to run the pipeline. Data were processed with MCMICRO and the output was used for cylinter analysis. Here's the error I get:

MainProcess 2024-12-09 13:19:26,396 INFO: Check if all cell IDs from the CSV are represented in the segmentation mask
Traceback (most recent call last):
  File "/opt/miniconda3/envs/cylinter/bin/cut_cells", line 10, in <module>
    sys.exit(cut())
  File "/opt/miniconda3/envs/cylinter/lib/python3.10/site-packages/cellcutter/cli.py", line 156, in cut
    cut_mod.process_image(
  File "/opt/miniconda3/envs/cylinter/lib/python3.10/site-packages/cellcutter/cut.py", line 197, in process_image
    raise ValueError(
ValueError: 25 cell IDs in the CELL_DATA CSV file are not represented in the segmentation mask. Please check that the segmentation mask contains all cell IDs present in the CSV file. The first 10 problematic IDs are 39479 38583 21761 16984 34553 20463 38500 21942 24365 22678
Traceback (most recent call last):
  File "/opt/miniconda3/envs/cylinter/bin/cylinter", line 10, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/cylinter/lib/python3.10/site-packages/cylinter/cylinter.py", line 49, in main
    pipeline.run_pipeline(config, args.module)
  File "/opt/miniconda3/envs/cylinter/lib/python3.10/site-packages/cylinter/pipeline.py", line 129, in run_pipeline
    data = module(data, qc, config)  # getattr(qc, module)
  File "/opt/miniconda3/envs/cylinter/lib/python3.10/site-packages/cylinter/components.py", line 56, in wrapper
    result = func(*args, **kwargs)
  File "/opt/miniconda3/envs/cylinter/lib/python3.10/site-packages/cylinter/modules/curateThumbnails.py", line 232, in curateThumbnails
    z_img = zarr.open(z_path_img, mode='r')
  File "/opt/miniconda3/envs/cylinter/lib/python3.10/site-packages/zarr/convenience.py", line 137, in open
    raise PathNotFoundError(path)
zarr.errors.PathNotFoundError: nothing found at path ''

Any suggestion would be highly appreciated.

Thank you!

**Comment by gjbaker** [comment]
Hi @fotisn7!

Thank you for your interest in CyLinter. The error stems from a subprocess call to a Python library used by the CyLinter to crop image patches from larger multiplex images called cellcutter (https://github.com/labsyspharm/cellcutter); this tool is also maintained by the Laboratory of Systems Pharmacology. The error indicates that (for one reason or another) there are cell IDs in the "CellID" column of the spatial feature table passed to the curateThumbnails module (and subsequently to cellcutter) that are not in the image segmentation mask which is also being passed to the program. This can happen for a number of different reasons, so you may have to do a bit of digging to figure out why. However, we have seen these types of mismatches in the past when a particular image has been segmented on multiple occasions using different segmentation parameters and a spatial feature table from one run and a segmentation mask from another are passed to cellcutter as a pair. These two objects will likely have different numbers of segmented cells, and therefore the cell IDs will not match. When this happens, you get the error you see here.

Please let us know if we can be of any further assistance.

Best,
-Greg
